### ISSUE TITLE
Typo in readme for Connector/python

### ISSUE THREAD

**Issue by reillski** [aws/aws-advanced-python-wrapper#553]
### Describe the issue

There is a small typo in the readme. I think it should be “MySQL Connector/Python” instead of “connection/python”

> To use the driver with MySQL Connection/Python, see the following example:

Thanks!
Marc

### Links

https://github.com/aws/aws-advanced-python-wrapper

**Comment by karenc-bq** [comment]
Hi @reillski, thank you for spotting the typo and for raising this issue, we have addressed it in #554.
